import Foundation

/// The licensed EmojiOne set, compiled in like every other shipped list.
/// Nothing here is fetched or replaced at runtime.
///
/// Artwork: EmojiOne v1 by Emoji One, CC BY-SA 4.0
/// (https://creativecommons.org/licenses/by-sa/4.0/). Share-alike: the
/// artwork may be redistributed and used commercially with attribution,
/// and any modification of the artwork itself must be shared under the
/// same licence. Bundling it is a collection rather than an adaptation,
/// and a change of format alone never creates one, so this does not put
/// the application under share-alike — but redrawing these icons in
/// place would.
///
/// Split across files only so the compiler can build the set in
/// parallel. Generated by scripts/import-emojione-icons.py; edit the
/// artwork and rerun it rather than editing these files.
enum EmojiOneIconCatalogData {
    static let icons: [ClearframeIcon] = EmojiOneIconCatalogData0.icons + EmojiOneIconCatalogData1.icons + EmojiOneIconCatalogData2.icons + EmojiOneIconCatalogData3.icons + EmojiOneIconCatalogData4.icons + EmojiOneIconCatalogData5.icons + EmojiOneIconCatalogData6.icons + EmojiOneIconCatalogData7.icons
}
